//untuk pengujian API file ini dapat di hapus nantinya hanya untuk menguji API berjalan atau tidak

GET http://localhost:5000/products


###
GET http://localhost:5000/products/2

###
POST  http://localhost:5000/products
Content-Type: application/json

{
    "title" : "Product 2",
    "price" : 10.000
}


###
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
    "title" : "Product 1",
    "price" : 123
}

###
DELETE  http://localhost:5000/products/1